---
title: EC2104 Lecture 3 - Single Variable Optimization
author: ling
output:
    beamer_presentation:
        slide_level: 3
        toc: false
theme: "Madrid"
---

# Implicit Differentiation

Solving $\frac{dy}{dx}$ without an explicit function

Steps:

1. Take derivatives of both side with respect to $x$
2. Solve for $\frac{dy}{dx}$

E.g. Solve $\frac{dy}{dx}$ for $y^2 + xy = 5$

1. $2y\frac{dy}{dx}+y+x\frac{dy}{dx}=0$
2. $\frac{dy}{dx}=\frac{-y}{2y+x}$

## Differentiating Inverse Function

Common trick used in probability to retrieve transformed
random variable

\begin{block}{Differentiating Inverse Function}
If $x_0$ is an interior point of interval $l$ and
$f'(x_0)\neq 0$, then $g$ is differentiable at $y_0=f(x_0)$
and 
\begin{align*}
    g'(y_0) = \frac{1}{f'(x_0)}
\end{align*}
\end{block}

# Taylor Approximation


\begin{block}{nth-order Taylor polynomial}
Approximate the function $f(x)$ around $x=a$
\begin{align*}
f(x) &\approx \sum_{k=0}^n \frac{f^{(k)}(a)}{k!}(x-a)^k
\end{align*}
\end{block}

- Building block in many numerical approximation for solving
optimization problems.
    - Besides economics, machine learning and operational
      research field heavily uses this approximation in
      their algorithms.
- Note that we are approximating $f(x)$ at a point $a$
  - When $a$ change, the approximated value $\tilde{y}$
    changes
- Error of approximation ($\tilde{y}-y$) increase as $x$
  moves further away from $a$
- Note:
  - $0!=1, n! = n\times(n-1)\times(n-2)\times \cdots \times 2\times 1$
  - $f^{(k)}(a)$ is the $k$th derivatives evaluated at $a$

# Convexity

Key building blocks used in many techniques, including
optimization

\begin{block}{Convexity}
A function is said to be convex if for any $a, b$ and for
any $t \in[0, 1]$
\begin{align*}
    f(ta+(1-t)b) \leq tf(a) + (1-t)f(b)
\end{align*}
\end{block}

- Strictly convex if 
  $f(ta+(1-t)b) > tf(a) + (1-t)f(b)$
- Concave function when 
  $f(ta+(1-t)b) \geq tf(a) + (1-t)f(b)$
  - Strictly concave when 
  $f(ta+(1-t)b) < tf(a) + (1-t)f(b)$
- Note that a concave function is the negative of convex
  function
  - If $f(x)$ is concave, then $-f(x)$ is convex
- Why study convex problem?
  - For a convex minimization problem, a local minimizer is
    also a global minimizer ( which is in general not true
    for other type of problem! )

## Testing Convexity with second derivative

\begin{block}{Second derivative test for convexity}
Suppose that $f$ is continuous in the interval $l$ and twice
differentiable is in the interior of $l$. Then:
\begin{itemize}
    \item $f''(x)>0\Rightarrow f(x)$ is strictly convex in $l$
    \item $f''(x)\geq0\Rightarrow$ convex only
    \item $f''(x)<0\Rightarrow f(x)$ is strictly concave in $l$
    \item $f''(x)\leq0\Rightarrow$ concave only
\end{itemize}
\end{block}

# Single variable optimization

## Extreme Value Theorem

Useful to know if extrema exist (note: but it does not tell
you if extrema does not exist)

\begin{block}{Extreme Value Theorem}
Suppose that $f$ is continuous function over a closed and
bounded interval $[a, b]$. Then there exist point a minimum
point $d$ and a maximum point $c$
\end{block}

- Must be continuous
- Must be closed (skipping formal definition)
  - Intuitively: point exist at the boundary
  - Closed: $[1, 2]$
  - Open: $(1, 2), (1, 2], [1, 2)$
- Must be bounded (skipping formal definition)
  - Intuitively: you can find a positive number $M$ that is
    larger than all the values in the set of values
  - points must not infinity

## Stationary/ critical/ turning points

\begin{block}{Stationary point or critical point}
Let $f: X \rightarrow R$, where $X$ is an open subset of
$R$. An interior point $x^*\in X$ is called a stationary
point of $f$ if $f'(x^*)=0$
\end{block}

Types of stationary points:

1. Maximum point
2. Minimum point
3. Inflection point (saddle point)

Q: How do we know what is the type of stationary points? 

- First derivative test
- Second derivative test

## Finding extrema using turning points


\begin{block}{First Order Necessary Condition}
If $x^*$ is a local minimizer of $f$ and $f$ is continuously
differentiable in an open neighbourhood of $x^*$, then
\begin{align*}
    \frac{d}{dx} f(x^*) = 0
\end{align*}
\end{block}

- Note: FOC are only necessary conditions for extrema ($P\Rightarrow Q$)
  - If $x^*$ is a local minimizer/maximizer of $f$ on the
    domain,then $x^*$ is a stationary point ($\Rightarrow
    f'(x)=0$).
  - Provided the function is differentiable at the point
- Given a turning point, it is uncertain if it's min/max
  point
  - $P\Leftarrow Q$ not clear,
  so is $x^*$ a max? min? or inflection?
- Other points that are extrema but might not satisfy FOC
    - Extreme points
    - Non-differentiable points

## Testing identify of turning points using First Derivative Test

\begin{block}{Condition for First Derivative Test}
Assume 1. Interior point 2. Function is differentiable
within the neighbourhood (a, b) of the stationary point at c
\end{block}

$f'(a)$ | $f'(c)$ | $f'(b)$ | result
--- | --- | --- | ---
$\geq0$ | $=0$ | $\leq0$ | local max
$\leq0$ | $=0$ | $\geq0$ | local min
$> 0$ | $=0$ | $> 0$ | not a extrema
$< 0$ | $=0$ | $< 0$ | not a extrema

Intuitively: gradient is the slope, draw the different cases

## Testing identify of turning points using Second Derivative Test

\begin{block}{Condition for Second Derivative Test}
Assume 1. Interior point 2. Function is twice differentiable
at $x=c$ where $f'(c)=0$ (stationary point)
\end{block}

$f''(c)$ | result
--- | ---
$\leq 0$ | local max
$< 0$ | strict local max
$\geq 0$ | local min
$> 0$ | strict local min
$=0$ | no results

Note:

- Recall the property of convex function $f''(x) \geq 0
  \forall x$
- Therefore, a stationary point in the convex function is
  always the min

## Determine point of inflection

Recall: second derivative test say nothing about $f''(c)=0$

\begin{block}{Definition for Inflection points}
If function $f$ is twice differentiable, the point $c$ is
called an inflection point for $f$ if there exists an
interval $(a, b)$ about $c$ such that
\begin{itemize}
    \item $f''(x) \geq 0 $ in $(a, c)$ and $f''(x)\leq0$ in
    $(c, b)$
    \item $f''(x) \leq 0$ in $(a, c)$ and $f''(x) \geq 0$ in
    $(c, b)$
\end{itemize}
\end{block}

\begin{block}{Test for Inflection Points}
Let $f$ be a function with a continuous second derivative in
an interval $l$, and let $c$ be an interior point of $l$.
\begin{itemize}
    \item If $c$ is an inflection point for f, then
    $f''(c)=0$
    \item If $f''(c)=0$ and $f''$ changse sign at $c$, then
    $c$ is an inflection point for $f$
\end{itemize}
\end{block}

## Note on Global vs Local Extrema

Extreme points are points where functions reach their
highest/lowest values

\begin{block}{Extrema}
If $f(x)$ has domain $D$,
\begin{itemize}
    \item $c \in D$ is maximum point for $f\Leftrightarrow
    f(x) \leq f(c), \forall x \in D$
    \item $d \in D$ is maximum point for $f\Leftrightarrow
    f(x) \geq f(c), \forall x \in D$
\end{itemize}
\end{block}
- Local extrema when the point is max/min point in a
  neighbourhood (within a interval of values)
- Global extrema when the point is max/min point across all
  the domain
- Generally, a function will have multiple local extrema
    - Only for a special subset of functions, the local extrema
      = global extreme (when functions are strictly
      convex/concave)
    - Determining global extrema remain an unsolved problem
      outside of convex functions. Best way is to compare
      the functional values

## Summary on finding the extrema of functions

\begin{block}{Setup}
    Find maximum/minimum values of a differentiable function
    $f$ defined on a closed, bounded interval $[a, b]$
\end{block}

Then the General step for finding the extrema:

1. Consider interior point
   - Using First Order Condition (FOC)
2. Consider boundary (end points)
   - In the case of the setup, $f(a), f(b)$
3. Consider non-differentiable points

Compare the functional values to determine global extrema

\begin{block}{Determine extrema of unbounded functions}
Value of extreme must be found through methods of limits
\end{block}
