---
title: EC2104 an overview from my perspective
author: ling
output:
    pdf_document:
        toc: true
        toc_depth: 4
---

# What do you need to know

EC2104 is meant to cover the mathematics (linear algebra and
calculus) needed for undergraduate economics study. The
contents covered in this module is representative of the
main contents covered in 5 mathematics modules.
Therefore, the module is heavily focusing on applied and not
proving.

In a layman term: you need to know how to use the tools but
you are not expected to know how are those tools built.

Using an analogy: if this module is a microwave (those you
have at home), what you need to know is what kind of food
can be put inside the microwave (e.g. eggs should not be
placed in microwave) and how to operate the timer,
intensity of the microwave. Bonus might be to understand
basic theory behind how microwave functions to make your own 
decisions on if an unknown food item can be placed in the
microwave.
However, you are not expected to work out the engineering
logic behind the microwave. For example, how to design the
circuit board to minimise possibility of short-circuit (I
don't know much about engineering).

If you are interested to know how the definitions and
theorems are derived, I strongly recommend you to audit
or take the following modules for credit.

| Content | Module |
| ---|--- |
Single Variable Calculus | MA2002 Calculus
Multi-Variable Calculus | MA2104 Multivariable Calculus OR MA2311 Techniques in Advanced Calculus
Linear Algebra | MA2001 Linear Algebra I
Multi-Variable Optimization (Linear problems) | MA3252 Linear and Network Optimisation
Multi-Variable Optimization (Non-Linear problems) | MA3236 Non-Linear Programming

# How do you master EC2104

Since EC2104 emphasis on applied mathematics, the best way
to ace this module and the content is to... apply them.
One shall not ponder too long on why those methods works but
focus on how to apply those methods in different context.

For the purpose of this method, it might be less useful to
understand why limits are called limits than to solve the
$\lim_{x\rightarrow \infty}x^2/e^x$
If you are interested in knowing the why, please refer to
["What do you need to know"](#What%20do%20you%20need%20to%20know)
section on the modules offered by mathematics department.

Therefore, attempt every single tutorials and revise the
weekly quiz.
