---
title: EC2104 Tutorial 1 solution
author: ling
output:
    beamer_presentation:
        slide_level: 2
        toc: false
theme: "Madrid"
---

# Question 1: Finding limits

## Before finding limits

Before you apply fancy L'Hopital rule or any other techniques

1. Check if limit exist (left limit = right limit)
   - There is no point trying to find something that does
     not exist
2. Check if the limit is in indeterminate form 
   ($\frac{0}{0}, \frac{\infty}{\infty}, 0\cdot0,
   \infty\cdot\infty$)
   - If there is a solution simply by substituting the value
     of the limit (e.g. $\lim_{x\rightarrow0}x+4=0+4=4$), 
     why bother wasting time
3. If limit is in indeterminate form and value tends towards
   infinity, check if denominator has higher rate of growth
   than numerator
   - Intuitively, if only the denominator is infinity, the
     fraction will tends towards 0
   - Example: solve question 1a) $\lim_{x\rightarrow \infty}
     \frac{x}{e^x}=0$ by eyeballing
   - Order of growth (when value tends towards
     infinity only): $O(1) < O(log(x))
     < O(x^n) < O(e^x)$
   - note: require strong intuition and might be hard to
     observe for more complicated questions

## Question 1b)

Q: Find
$\lim_{x\rightarrow-4}\left(\frac{x^2-16}{x+4}\right)\ln|x|$

0. Identify: $\ln|-4|=ln(4)$ is a constant

Method 1: Simplification

1. Observe $x^2-16=(x+4)(x-4)$
2. Simplify question: 
$\lim_{x\rightarrow-4}\left(\frac{x^2-16}{x+4}\right)\ln|x|
= \lim_{x\rightarrow-4}(x-4)\ln|x|=-8\ln(4)$

Method 2: L'H

1. Since the fraction is indeterminate, apply L'H:
   $\Rightarrow
   \lim_{x\rightarrow-4}\frac{\frac{d}{dx}x^2-16}{\frac{d}{dx}x+4}\ln|-x|
   =\lim_{x\rightarrow -4}\frac{2x}{1}\ln|-x|=-8\ln(4)$

Why bother with other methods when almost all questions can
be solved by L'H?

- Solving differentiation can be challenging sometimes

## Question 1c)

Q: Find
$\lim_{x\rightarrow 1.5}\frac{2x^2-3x}{|2x-3|}=
\lim_{x\rightarrow 1.5}\frac{x(2x-3)}{|2x-3|}$

0. Observe:
   - although fraction is indeterminate, absolute
   function is not differentiable.
   - Therefore, L'H cannot be
   used directly
   - and we cannot simplify the question
   directly.
   - We need to use piecewise function and find limit by
     finding the left limit and right limit
1. Left limit:
   $\lim_{x\rightarrow
   1.5}\frac{x(2x-3)}{-(2x-3)}=\lim_{x\rightarrow 1.5}-x=-1.5$
2. Right limit:
   $\lim_{x\rightarrow
   1.5}\frac{x(2x-3)}{2x-3}=\lim_{x\rightarrow 1.5}x=1.5$
3. Observe: since left limit $\neq$ right limit, by
   definition of limits the limit does not exist

## Question 1d): challenging but important

Q: Find
$\lim_{x\rightarrow\infty}\sqrt{x^2+x}-x$

0. Observe:
   - The question is not in a fraction form, L'H
   cannot be applied directly.
   - Although $\sqrt{x^2+x}>0$ but $-x<0$, and it seems like
     $\sqrt{x^2+x}\approx x$. So it is hard to decide if the
     limit will diverge (positive or negative infinity) or
     it will converge
1. Use an important trick in solving limits question:
   $\lim_{x\rightarrow\infty}\sqrt{x^2+x}-x
   =\lim_{x\rightarrow
   \infty}\frac{(\sqrt{x^2+x}-x)(\sqrt{x^2+x}+x)}{(\sqrt{x^2+x}+x)}$
   - Note: since
     $\frac{(\sqrt{x^2+x}+x)}{(\sqrt{x^2+x}+x)}=1$, we can
     multiply any functions with $1$ without changing the
     function.
   - Note: furthermore, we simplify the function using
     identity: $(a+b)(a-b)=a^2-b^2$
2. Therefore, $\lim_{x\rightarrow \infty}\sqrt{x^2+x}-x
   =\lim_{x\rightarrow \infty} \frac{x^2+x-x^2}{\sqrt{x^2+x}+x}$
   - to be continued in the next slide

## Question 1d) cont

Now, we solve
$\lim_{x\rightarrow \infty} \frac{x^2+x-x^2}{\sqrt{x^2+x}+x}
=\lim_{x\rightarrow \infty} \frac{x}{\sqrt{x^2+x}+x}$

3. Reapplying the trick in step (1):
    - $\lim_{x\rightarrow \infty} \frac{x}{\sqrt{x^2+x}+x}
    =\lim_{x\rightarrow \infty} \frac{x}{\sqrt{x^2+x}+x} \cdot
    \frac{1/x}{1/x}=
    \lim_{x\rightarrow \infty} \frac{1}{\sqrt{1+\frac{1}{x^2}}+1}$
4. Deduce: 
$\lim_{x\rightarrow \infty} \frac{1}{\sqrt{1+\frac{1}{x^2}}+1}
=\frac{1}{2}$

Note: We skipped some detailed working here, you can refer
to the step by step procedure in tutorial solution or work
it out yourself.

## Question 1e)

Similar idea as question 1d), refer to tutorial solution for
detailed steps.

## Question 1f)

Q: Find $a, b$ such that
$\lim_{x \rightarrow 0}\frac{\sqrt{ax+b}-2}{x}=1$

0. For L'Hopital to work, assume
 $\lim_{x \rightarrow 0} \sqrt{ax+b}-2=0
 \Rightarrow \sqrt{b} = 2
 \Rightarrow b = 4$
1. Applying L'Hopital rule:
 $\Rightarrow \lim_{x \rightarrow 0}\frac{a}{2\sqrt{ax+b}}=1$
2. Substitute $x=0$:
 $\Rightarrow \frac{a}{2\sqrt{b}}=1$
3. Find relationship between $a, b$:
 $\Rightarrow a = 2\sqrt{b}$
4. Since from step (0): $b = 4 \Rightarrow a = 4$

# Question 2: Finding equilibrium

Important things to know:

- Competitive market always clears
  - quantity demanded = quantity supplied, $Q_S = Q_D$
  - Assumes no regulations and firms, buyers have no market
    power (perfect competition)
- To solve the equilibrium (the easier way):
  - $1, 2$ variables: substitution
  - $\geq 2$ variable: matrix operations (linear algebra)
- A shift in line when intercept changes, a rotation in line
  when gradient changes
  - $Q_S = 10P_J - 5 P_A \Rightarrow P_J = \frac{Q_S}{10} +
    \frac{1}{2}P_A$
  - Note in plotting demand and supply curve, we usually
    plot price as the function output  (inverse demand and
    supply)
    $\Leftrightarrow P_J(Q_S) = f(Q_S) = \frac{Q_S}{10} +
    \frac{1}{2}P_A$
- When asked about price ceiling (max price),
  price floor (min price), check if the policy
  is binding first

# Question 3: Finding inverse 

## Question 3a

Q: $f(x) = \frac{1}{2}(e^x - e^{-x})$

1. Solve for $x$: $y=\frac{1}{2}(e^x - e^{-x})$
2. Multiply both side by $e^x$: $ye^x=\frac{1}{2}(e^{2x} - 1)$
3. Let $z=e^x$, solve for: $yz-\frac{1}{2}z^{2} + \frac{1}{2}=0$
   - $\Leftrightarrow$ solve $z^2-1-2yz=0$
4. $\Rightarrow z = y + \sqrt{y^2+1}$
   - Reject $z = y - \sqrt{y^2+1}$ since $z = e^x > 0$
5. Take $\ln$: $y = \ln(x+\sqrt{x^2+1})$

- Key trick: substituting the function of $x$

## Question 3b

Q: $f(x)=40x-4x^2, x\in[0, 10]$

1. Show function is not valid (not one-to-one) with numeric
   example: $f(4)=f(6)$

- Key learning point: if function is not one-to-one, the
  inverse function does not exist

# Question 4: Finding first derivatives

## Question 4a

Show $f$ is differentiable at $x=1$

\begin{align*}
f(x) = \begin{cases}
2+\sqrt{x}, & x\geq 1\\
\frac{1}{2}x + \frac{5}{2}, & x<1
\end{cases}
\end{align*}

- Key: show by definition (limit of Newton's quotient exist)

1. Write down the definition
   \begin{align*}
   f'(1) = \lim_{\Delta x\rightarrow 0} \frac{f(1+\Delta x)
   - f(1)}{\Delta x}
     =\lim_{\Delta x\rightarrow 0} \frac{f(1+\Delta x) - 3}{\Delta x}
   \end{align*}
2. Test if limit exist (left limit = right limit)
   - Left limit:
     $\lim_{\Delta x \rightarrow 0}\frac{2+\sqrt{1+\Delta x}-3}{\Delta x}=\frac{1}{2}$
   - Right limit:
     $\lim_{\Delta x \rightarrow 0}\frac{\frac{1}{2}(1+\Delta x)+\frac{5}{2}-3}{\Delta x}=\frac{1}{2}$
3. Since limit exist, $f$ is differentiable at $x=1$ and
   $f'(1)=\frac{1}{2}$

## Question 4b

Determine if $f$ is differentiable at $x=2$,
$f(x)=\begin{cases}\frac{1}{4}x^3-\frac{1}{2}x^2, &x\geq 2\\
\frac{-6x-6}{x^2+2}, &x<2\end{cases}$

- Note that non-continuous function are not differentiable

0. For a quick check, try if $f(2)$ from the left equals to
   the right
1. More formally:
   - Left limit ($x < 2$):
     $\lim_{x\rightarrow 2^-}f(x)=
     \frac{-6\times2-6}{2^2+2}=-3$
   - Right limit ($x \geq 2$):
     $\lim_{x\rightarrow 2^+}f(x)=
     \frac{1}{4}2^3-\frac{1}{2}2^2=0$
2. Since limit does not exist (left limit not equal to right
   limit), function is not continuous at $x=2$ and is not
   differentiable

# Question 5: Finding roots with Intermediate Value Theorem

## Question 5a

Q: Use IVT to show $2^x=\frac{10}{x}$ for some $x>0$

0. Express function in a more familiar way:
   $\Rightarrow 2^x-\frac{10}{x}=0$
1. Check if function is continuous in the domain
   - Note: although function is not continuous in the whole
     real line, when restricted to only positive values the
     function is continuous
2. Find alternating functional value. For example: $f(2)<0,
   f(3)>0$
3. Invoke IVT
   - By IVT, there exists at least one value $c$
   in $[2, 3]$ such that $f(c)=2^c-\frac{10}{c}=0$

## Question 5b

Q: Can we use IVT to conclude function has no roots in the
interval?

- No, IVT only allows us to conclude there exists at least
  one root.
- In Math and Logic, one way deduction is different from two
  way deduction ($P \Rightarrow Q \neq P \Leftarrow Q$)
  - If a definition/theorem works two ways, we say it is
    both a necessary and sufficient condition, or say P if
    and only if Q $P \Leftrightarrow Q$
- Example: $f(x)=(x-1)^2$
  - $f(0)=1=f(2)>0$, but $f(1)=0\Rightarrow$ there is at
    least one root

# Question 6: Elasticity

Given:

- $P_{t-1}=\$20$
- $Q_{t-1}=100$ mil
- PED $=\epsilon_D = -0.25$
- PES $=\epsilon_S = 0.5$
- demand function: $Q_d=a-bP$
- supply function: $Q_s = c+dP$

Q6a: Solve for demand and supply function

1. Demand function:
   $\epsilon_D = \frac{d Q_d}{d P}\left(\frac{P}{Q_d}\right)
   = -b \frac{20}{100}=-0.25$ $\Rightarrow b=1.25$
   - Since $Q_d = a - bP \Rightarrow 100 = a - 1.25\cdot 20
     \Rightarrow a = 125$
   - Therefore: $Q_d = 125 - 1.25P$
2. Supply function:
   $\epsilon_S = \frac{d Q_s}{d P}\left(\frac{P}{Q_s}\right)
   = d \frac{20}{100}=0.5$ $\Rightarrow d=2.5$
   - Since $Q_s = c - dP \Rightarrow 100 = c - 2.5\cdot 20
     \Rightarrow c = 50$
   - Therefore: $Q_S = 50 + 2.5 P$

## Question 6b

- Demand and Supply have same slope, different intercepts
  - Shift in demand and supply
- Name any factor that shifted demand and supply
